easy_admin:
    entities:
        # List the entity class name you want to manage
      Acteur:
        class: App\Entity\Acteur
        form:
          fields:
            - {property: 'prenom', type: 'text'}
            - {property: 'nom', type: 'text'}
            - {property: 'date_naissance', label: 'Date de Naissance', type_options: {widget: 'single_text'}}
            - {property: 'nationalite', label: 'Nationalite', type: 'text'}
      Film:
        class: App\Entity\Film
        form:
          fields:
            - {property: 'titre', type: 'text'}
            - {property: 'annee_Production', type_options: {widget: 'single_text'}}
            - {property: 'note', type: 'number'}
            - {property: 'synopsis'}
            - {property: 'cover', type: 'url'}
            - {property: 'bande_annonce', type: 'url'}
            - {property: 'producteurs', label: 'Producteurs', type: 'easyadmin_autocomplete', type_options:{class: 'App\Entity\Producteur'}}
            - {property: 'editeur', label: 'Editeur', type: 'entity', type_options: { choice_label: 'fullName'}}
            - {property: 'acteurs', label: 'Acteurs', type: 'entity', type_options: { choice_label: 'fullName', multiple: 'true'}}
            - {property: 'tags'}
            - {property: 'genres', label: 'Genres', type: 'entity', type_options: {choice_label: 'categorie', multiple: 'true', class: 'App\Entity\Genre'}}
      Editeur:
        class: App\Entity\Editeur
        form:
          fields:
            - {property: 'prenom', type: 'text'}
            - {property: 'nom', type: 'text'}
            - {property: 'date_naissance', label: 'Date de Naissance', type_options: {widget: 'single_text'}}
            - {property: 'nationalite', label: 'Nationalite', type: 'text'}
      Genre:
        class: App\Entity\Genre
        form:
          fields:
            - {property: 'categorie', type: 'text'}
      Producteur:
        class: App\Entity\Producteur
      Tag:
        class: App\Entity\Tag
      Personne:
        class: App\Entity\Personne
