easy_admin:
    formats:
      number: '%0.1f'
    entities:
        # List the entity class name you want to manage
      Actor:
        class: App\Entity\Actor
        label: 'Acteur'
        list:
          title: 'Acteurs'
          fields: [{property: 'firstName', label: 'Prénom'},{property: 'name', label: 'Nom de Famille'},{property: 'photo', label: 'Photo', type: 'image'},{property: 'birthDate', label: 'Date de Naissance'},{property: 'nationality', label: 'Nationalité'},{property: 'films', label: "Films de l'acteur"}]
        form:
          fields:
            - {property: 'firstName', type: 'text'}
            - {property: 'name', type: 'text'}
            - {property: 'photo', type: 'text'}
            - {property: 'birthDate', label: 'Date de Naissance', type_options: {widget: 'single_text'}}
            - {property: 'nationality', label: 'Nationalite', type: 'text'}
      Film:
        class: App\Entity\Film
        label: 'Film'
        list:
          title: 'Films'
          fields: [{property: 'Title', label: 'Titre'},{property: 'cover', label: 'Affiche du Film', type: 'image'},{property: 'producers', label: 'Producteurs'},{property: 'actors', label: 'Acteurs'},{property: 'note', label: 'Note'},{property: 'tags', label: 'Tags'}]
        form:
          fields:
            - {property: 'title', type: 'text'}
            - {property: 'productionDate', type_options: {widget: 'single_text'}}
            - {property: 'note'}
            - {property: 'synopsis'}
            - {property: 'cover', type: 'url'}
            - {property: 'teaser', type: 'url'}
            - {property: 'producers', label: 'Producteurs', type: 'entity', type_options:{choice_label: 'fullName', multiple: 'true', class: 'App\Entity\Producer'}}
            - {property: 'editor', label: 'Editor', type: 'entity', type_options: { choice_label: 'name', class: 'App\Entity\Editor'}}
            - {property: 'actors', label: 'Acteurs', type: 'entity', type_options: { choice_label: 'fullName', multiple: 'true', class: 'App\Entity\Actor'}}
            - {property: 'tags', label: 'Tags', type: 'entity', type_options: {choice_label: 'name', multiple: 'true', class: 'App\Entity\Tag'}}
            - {property: 'genres', label: 'Genres', type: 'entity', type_options: {choice_label: 'category', multiple: 'true', class: 'App\Entity\Genre'}}
      Editor:
        class: App\Entity\Editor
        label: 'Editeur'
        list:
          title: 'Editeurs'
          fields: [{property: 'name', label: 'Nom du Studio'},{property: 'nationality', label: 'Nationality'}]
        form:
          fields:
            - {property: 'name', type: 'text'}
            - {property: 'nationality', label: 'Nationalite', type: 'text'}
      Genre:
        class: App\Entity\Genre
        label: 'Genre'
        list:
          title: 'Genres'
          fields: [{property: 'category', label: 'Genre Cinématographique'}]
        form:
          fields:
            - {property: 'category', type: 'text'}
      Producer:
        class: App\Entity\Producer
        label: 'Producteur'
        list:
          title: 'Acteurs'
          fields: [{property: 'firstName', label: 'Prénom'},{property: 'name', label: 'Nom de Famille'},{property: 'nationality', label: 'Nationalité'}]
        form:
          fields:
          - {property: 'firstName', type: 'text'}
          - {property: 'name', type: 'text'}
          - {property: 'birthDate', label: 'Date de Naissance', type_options: {widget: 'single_text'}}
          - {property: 'nationality', label: 'Nationalite', type: 'text'}
      Tag:
        class: App\Entity\Tag
        label: 'Tag'
        list:
          title: 'Acteurs'
          fields: [{property: 'name', label: 'Tag'}]
        form:
          fields:
            - {property: 'name', label: 'Tag', type: 'text'}
    design:
      menu:
        - { entity: 'Actor', icon: 'male' }
        - { entity: 'Editor', icon: 'building' }
        - { entity: 'Film', icon: 'film' }
        - { entity: 'Genre', icon: 'clipboard' }
        - { entity: 'Producer', icon: 'play' }
        - { entity: 'Tag', icon: 'comment' }
    list:
      actions:
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'trash', label: false }