easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Acteur
        - App\Entity\Editeur
        - App\Entity\Film
        - App\Entity\Genre
        - App\Entity\Personne
        - App\Entity\Producteur
        - App\Entity\Tag
